const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.BASE_URL||'http://127.0.0.1:4173/',{waitUntil:'networkidle'});
 assert.equal(await page.locator('.meeting-card').count(),3);
 await page.screenshot({path:'/tmp/minutes-desktop.png',fullPage:true});
 await page.locator('#search').fill('客户');assert.equal(await page.locator('.meeting-card').count(),1);
 await page.locator('#search').fill('');
 await page.locator('[data-filter=ready]').click();assert.equal(await page.locator('.meeting-card').count(),1);
 await page.locator('[data-filter=all]').click();
 await page.locator('.meeting-card').first().click();
 await page.locator('[data-source="1"]').click();assert.equal(await page.locator('#source-1').getAttribute('class'),'transcript-segment highlight');
 await page.locator('[data-field=summary]').fill('测试纪要：已完成编辑与保存。');
 await page.reload();await page.locator('.meeting-card').first().click();assert.equal(await page.locator('[data-field=summary]').innerText(),'测试纪要：已完成编辑与保存。');
 await page.locator('#confirm-meeting').click();assert.equal(await page.locator('#confirm-meeting').innerText(),'撤回确认');
 await page.locator('[data-field=summary]').fill('更新后的会议摘要。');assert.equal(await page.locator('#confirm-meeting').innerText(),'确认纪要');
 await page.locator('#add-action').click();assert.equal(await page.locator('#actions .action-row').count(),4);
 await page.locator('#actions input[type=checkbox]').last().check();assert(await page.locator('#actions .action-row').last().evaluate(e=>e.classList.contains('done')));
 await page.screenshot({path:'/tmp/minutes-workspace.png',fullPage:true});
 await page.locator('#preview').click();assert((await page.locator('#print-document').innerText()).includes('更新后的会议摘要。'));
 await page.locator('#print-theme').selectOption('formal');assert.equal(await page.locator('#print-document').getAttribute('class'),'formal');
 await page.pdf({path:'/tmp/minutes-sample.pdf',format:'A4',printBackground:true});
 await page.locator('#preview-dialog .close-dialog').click();
 await page.locator('#back').click();
 await page.locator('.new-meeting').first().click();
 await page.locator('[name=title]').fill('自定义测试会议 <script>alert(1)</script>');
 await page.locator('[name=transcript]').fill('原文：小林负责下周交付原型。');
 await page.locator('#create-form [type=submit]').click();assert.equal(await page.locator('.workspace-heading h1').innerText(),'自定义测试会议 <script>alert(1)</script>');
 assert.equal(await page.locator('[data-field=raw]').innerText(),'原文：小林负责下周交付原型。');
 await page.locator('[data-field=raw]').fill('编辑后的原文');await page.reload();await page.locator('.meeting-card').first().click();assert.equal(await page.locator('[data-field=raw]').innerText(),'编辑后的原文');
 await page.locator('#back').click();await page.locator('.new-meeting').first().click();await page.locator('[data-input=audio]').click();await page.locator('[name=title]').fill('录音测试');
 await page.locator('#audio-file').setInputFiles({name:'test.wav',mimeType:'audio/wav',buffer:Buffer.from('RIFFtest')});await page.locator('#create-form [type=submit]').click();assert.equal(await page.locator('audio').count(),1);
 await page.locator('#back').click();await page.locator('#try-demo').click();await page.locator('.workspace-heading').waitFor();assert((await page.locator('.workspace-banner').innerText()).includes('预设'));
 await page.setViewportSize({width:390,height:844});await page.locator('#back').click();await page.screenshot({path:'/tmp/minutes-mobile.png',fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.locator('.meeting-card').first().click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.screenshot({path:'/tmp/minutes-mobile-workspace.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('PASS: filters, source links, autosave/reload, confirmation invalidation, tasks, PDF rendering, custom text/XSS, audio selection, demo, mobile overflow, no JS errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
